# Generated by Django 4.0.5 on 2022-07-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('house', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sum', models.DecimalField(decimal_places=0, max_digits=8)),
                ('remain', models.DecimalField(decimal_places=0, max_digits=8)),
                ('pos', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('s_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('m_id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('u_id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('left_borrow', models.DecimalField(decimal_places=0, max_digits=2)),
                ('left_order', models.DecimalField(decimal_places=0, max_digits=2)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.bookinfo')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateTimeField()),
                ('on_date', models.DateTimeField()),
                ('r_date', models.DateTimeField(null=True)),
                ('renew_num', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.bookstate')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo')),
            ],
        ),
    ]
